// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=mocks_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	reflect "reflect"

	manifest "github.com/Clawdlinux/agent-native-format/pkg/manifest"
	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockResolver) Resolve(intent string, hints []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", intent, hints)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder) Resolve(intent, hints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver)(nil).Resolve), intent, hints)
}

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
	isgomock struct{}
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockBuilder) Build(req manifest.ContextRequest, capabilities []string) (manifest.ExecutionManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", req, capabilities)
	ret0, _ := ret[0].(manifest.ExecutionManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockBuilderMockRecorder) Build(req, capabilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockBuilder)(nil).Build), req, capabilities)
}

// MockFeedbackSink is a mock of FeedbackSink interface.
type MockFeedbackSink struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackSinkMockRecorder
	isgomock struct{}
}

// MockFeedbackSinkMockRecorder is the mock recorder for MockFeedbackSink.
type MockFeedbackSinkMockRecorder struct {
	mock *MockFeedbackSink
}

// NewMockFeedbackSink creates a new mock instance.
func NewMockFeedbackSink(ctrl *gomock.Controller) *MockFeedbackSink {
	mock := &MockFeedbackSink{ctrl: ctrl}
	mock.recorder = &MockFeedbackSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackSink) EXPECT() *MockFeedbackSinkMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockFeedbackSink) Record(event manifest.FeedbackEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockFeedbackSinkMockRecorder) Record(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockFeedbackSink)(nil).Record), event)
}
