// Code generated by MockGen. DO NOT EDIT.
// Source: translator.go
//
// Generated by this command:
//
//	mockgen -source=translator.go -destination=mock_translator_test.go -package=acp
//

// Package acp is a generated GoMock package.
package acp

import (
	context "context"
	reflect "reflect"

	acl "github.com/Clawdlinux/ninevigil-acp/pkg/acl"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslator is a mock of Translator interface.
type MockTranslator[S any] struct {
	ctrl     *gomock.Controller
	recorder *MockTranslatorMockRecorder[S]
	isgomock struct{}
}

// MockTranslatorMockRecorder is the mock recorder for MockTranslator.
type MockTranslatorMockRecorder[S any] struct {
	mock *MockTranslator[S]
}

// NewMockTranslator creates a new mock instance.
func NewMockTranslator[S any](ctrl *gomock.Controller) *MockTranslator[S] {
	mock := &MockTranslator[S]{ctrl: ctrl}
	mock.recorder = &MockTranslatorMockRecorder[S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslator[S]) EXPECT() *MockTranslatorMockRecorder[S] {
	return m.recorder
}

// Name mocks base method.
func (m *MockTranslator[S]) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTranslatorMockRecorder[S]) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTranslator[S])(nil).Name))
}

// Translate mocks base method.
func (m *MockTranslator[S]) Translate(ctx context.Context, src S) (acl.Document, TranslateInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, src)
	ret0, _ := ret[0].(acl.Document)
	ret1, _ := ret[1].(TranslateInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslatorMockRecorder[S]) Translate(ctx, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslator[S])(nil).Translate), ctx, src)
}
