// Code generated by MockGen. DO NOT EDIT.
// Source: builder.go
//
// Generated by this command:
//
//	mockgen -source=builder.go -destination=mocks_test.go -package=builder
//

// Package builder is a generated GoMock package.
package builder

import (
	reflect "reflect"

	registry "github.com/Clawdlinux/agent-native-format/internal/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockToolSource is a mock of ToolSource interface.
type MockToolSource struct {
	ctrl     *gomock.Controller
	recorder *MockToolSourceMockRecorder
	isgomock struct{}
}

// MockToolSourceMockRecorder is the mock recorder for MockToolSource.
type MockToolSourceMockRecorder struct {
	mock *MockToolSource
}

// NewMockToolSource creates a new mock instance.
func NewMockToolSource(ctrl *gomock.Controller) *MockToolSource {
	mock := &MockToolSource{ctrl: ctrl}
	mock.recorder = &MockToolSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolSource) EXPECT() *MockToolSourceMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockToolSource) Lookup(capabilities []string) []registry.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", capabilities)
	ret0, _ := ret[0].([]registry.Tool)
	return ret0
}

// Lookup indicates an expected call of Lookup.
func (mr *MockToolSourceMockRecorder) Lookup(capabilities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockToolSource)(nil).Lookup), capabilities)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
