// Code generated by MockGen. DO NOT EDIT.
// Source: proxy.go
//
// Generated by this command:
//
//	mockgen -source=proxy.go -destination=mocks_test.go -package=proxy
//

// Package proxy is a generated GoMock package.
package proxy

import (
	context "context"
	http "net/http"
	reflect "reflect"

	manifest "github.com/Clawdlinux/agent-native-format/pkg/manifest"
	gomock "go.uber.org/mock/gomock"
)

// MockManifestStore is a mock of ManifestStore interface.
type MockManifestStore struct {
	ctrl     *gomock.Controller
	recorder *MockManifestStoreMockRecorder
	isgomock struct{}
}

// MockManifestStoreMockRecorder is the mock recorder for MockManifestStore.
type MockManifestStoreMockRecorder struct {
	mock *MockManifestStore
}

// NewMockManifestStore creates a new mock instance.
func NewMockManifestStore(ctrl *gomock.Controller) *MockManifestStore {
	mock := &MockManifestStore{ctrl: ctrl}
	mock.recorder = &MockManifestStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestStore) EXPECT() *MockManifestStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockManifestStore) Get(manifestID string) (*manifest.ExecutionManifest, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", manifestID)
	ret0, _ := ret[0].(*manifest.ExecutionManifest)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManifestStoreMockRecorder) Get(manifestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManifestStore)(nil).Get), manifestID)
}

// MockInjector is a mock of Injector interface.
type MockInjector struct {
	ctrl     *gomock.Controller
	recorder *MockInjectorMockRecorder
	isgomock struct{}
}

// MockInjectorMockRecorder is the mock recorder for MockInjector.
type MockInjectorMockRecorder struct {
	mock *MockInjector
}

// NewMockInjector creates a new mock instance.
func NewMockInjector(ctrl *gomock.Controller) *MockInjector {
	mock := &MockInjector{ctrl: ctrl}
	mock.recorder = &MockInjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInjector) EXPECT() *MockInjectorMockRecorder {
	return m.recorder
}

// Inject mocks base method.
func (m *MockInjector) Inject(ctx context.Context, manifestID string, action manifest.Action) (http.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inject", ctx, manifestID, action)
	ret0, _ := ret[0].(http.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inject indicates an expected call of Inject.
func (mr *MockInjectorMockRecorder) Inject(ctx, manifestID, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockInjector)(nil).Inject), ctx, manifestID, action)
}

// MockApprovalGate is a mock of ApprovalGate interface.
type MockApprovalGate struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalGateMockRecorder
	isgomock struct{}
}

// MockApprovalGateMockRecorder is the mock recorder for MockApprovalGate.
type MockApprovalGateMockRecorder struct {
	mock *MockApprovalGate
}

// NewMockApprovalGate creates a new mock instance.
func NewMockApprovalGate(ctrl *gomock.Controller) *MockApprovalGate {
	mock := &MockApprovalGate{ctrl: ctrl}
	mock.recorder = &MockApprovalGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalGate) EXPECT() *MockApprovalGateMockRecorder {
	return m.recorder
}

// IsApproved mocks base method.
func (m *MockApprovalGate) IsApproved(ctx context.Context, manifestID, actionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsApproved", ctx, manifestID, actionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsApproved indicates an expected call of IsApproved.
func (mr *MockApprovalGateMockRecorder) IsApproved(ctx, manifestID, actionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsApproved", reflect.TypeOf((*MockApprovalGate)(nil).IsApproved), ctx, manifestID, actionID)
}
