/*
Copyright 2026 Clawdlinux / NineVigil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package acl

import (
	"reflect"
	"strings"
	"testing"
)

func k8sExample() Document {
	return Document{
		Directives: []Directive{
			{Key: "cluster", Value: "prod-east"},
			{Key: "ns", Value: "payments"},
			{Key: "as-of", Value: "2026-05-03T12:34:56Z"},
		},
		Sections: []Section{
			{
				Name: "pods", Summary: "12/12 ok",
				Rows: []Row{
					{ID: "payment-api-7f8d", Count: 3, Fields: []Field{
						{"cpu", "42"}, {"mem", "61"}, {"r", "0"}, {"age", "3d"},
					}},
					{ID: "payment-worker-9a2b", Count: 2, Fields: []Field{
						{"cpu", "87"}, {"mem", "78"}, {"r", "3"}, {"age", "1d"},
					}, Flags: []string{"!"}},
					{ID: "payment-cron-1c4e", Count: 1, Fields: []Field{
						{"cpu", "5"}, {"mem", "12"}, {"r", "0"}, {"age", "7d"},
					}},
				},
			},
			{
				Name: "deploys", Summary: "3 all-avail",
				Rows: []Row{{ID: "payment-api", Fields: []Field{
					{"replicas", "3/3"}, {"strategy", "rolling"}, {"image", "v2.4.1"},
				}}},
			},
			{
				Name: "svcs", Summary: "2",
				Rows: []Row{{ID: "payment-api", Fields: []Field{
					{"type", "ClusterIP"}, {"port", "8080->8080"},
				}}},
			},
			{
				Name: "alerts", Summary: "1",
				Rows: []Row{{ID: "HighMemory", Fields: []Field{
					{"pod", "payment-worker-9a2b"}, {"at", "78"}, {"lim", "75"},
				}}},
			},
			{
				Name: "actions",
				Rows: []Row{{ID: "scale|rollout|restart|logs|describe"}},
			},
		},
	}
}

func TestEncodeGolden(t *testing.T) {
	t.Parallel()
	got, err := Encode(k8sExample())
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	want := "@cluster prod-east\n" +
		"@ns payments\n" +
		"@as-of 2026-05-03T12:34:56Z\n" +
		"\n" +
		"pods 12/12 ok\n" +
		"  payment-api-7f8d x3 cpu=42 mem=61 r=0 age=3d\n" +
		"  payment-worker-9a2b x2 cpu=87 mem=78 r=3 age=1d !\n" +
		"  payment-cron-1c4e x1 cpu=5 mem=12 r=0 age=7d\n" +
		"\n" +
		"deploys 3 all-avail\n" +
		"  payment-api replicas=3/3 strategy=rolling image=v2.4.1\n" +
		"\n" +
		"svcs 2\n" +
		"  payment-api type=ClusterIP port=8080->8080\n" +
		"\n" +
		"alerts 1\n" +
		"  HighMemory pod=payment-worker-9a2b at=78 lim=75\n" +
		"\n" +
		"actions\n" +
		"  scale|rollout|restart|logs|describe\n"
	if string(got) != want {
		t.Fatalf("encode mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRoundTrip(t *testing.T) {
	t.Parallel()
	in := k8sExample()
	enc, err := Encode(in)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	out, err := Decode(enc)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if !reflect.DeepEqual(in, out) {
		t.Fatalf("round trip mismatch.\n--- in ---\n%+v\n--- out ---\n%+v", in, out)
	}
	enc2, err := Encode(out)
	if err != nil {
		t.Fatalf("Encode2: %v", err)
	}
	if string(enc) != string(enc2) {
		t.Fatalf("re-encode not byte-stable")
	}
}

func TestQuotedValueRoundTrip(t *testing.T) {
	t.Parallel()
	in := Document{
		Sections: []Section{{
			Name: "logs",
			Rows: []Row{{ID: "nginx", Fields: []Field{
				{"cmd", "tail -n 100 /var/log/nginx.log"},
				{"msg", "needs `quoting`"},
			}}},
		}},
	}
	enc, err := Encode(in)
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	if !strings.Contains(string(enc), "`tail -n 100 /var/log/nginx.log`") {
		t.Fatalf("expected backtick quoting; got:\n%s", enc)
	}
	out, err := Decode(enc)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if !reflect.DeepEqual(in, out) {
		t.Fatalf("quoted round trip mismatch.\n--- in ---\n%+v\n--- out ---\n%+v", in, out)
	}
}

func TestDecodeRejectsTabs(t *testing.T) {
	t.Parallel()
	_, err := Decode([]byte("pods\n\tfoo cpu=1\n"))
	if err == nil || !strings.Contains(err.Error(), "tab") {
		t.Fatalf("expected tab rejection, got %v", err)
	}
}

func TestDecodeRejectsRowOutsideSection(t *testing.T) {
	t.Parallel()
	_, err := Decode([]byte("  orphan cpu=1\n"))
	if err == nil || !strings.Contains(err.Error(), "outside any section") {
		t.Fatalf("expected orphan-row rejection, got %v", err)
	}
}

func TestDecodeRejectsBadIndent(t *testing.T) {
	t.Parallel()
	_, err := Decode([]byte("pods\n foo cpu=1\n"))
	if err == nil || !strings.Contains(err.Error(), "exactly two spaces") {
		t.Fatalf("expected indent rejection, got %v", err)
	}
}

func TestDecodeStripsComments(t *testing.T) {
	t.Parallel()
	src := "# generated by acl-test\n@cluster c\n\n# inner comment\npods 1\n  a cpu=1\n"
	d, err := Decode([]byte(src))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if len(d.Directives) != 1 || d.Directives[0].Key != "cluster" {
		t.Fatalf("directive lost: %+v", d.Directives)
	}
	if len(d.Sections) != 1 || d.Sections[0].Name != "pods" {
		t.Fatalf("section lost: %+v", d.Sections)
	}
}

func TestEncodeRejectsBadInputs(t *testing.T) {
	t.Parallel()
	cases := map[string]Document{
		"empty section name": {Sections: []Section{{Name: ""}}},
		"section name space": {Sections: []Section{{Name: "bad name"}}},
		"empty directive":    {Directives: []Directive{{Key: ""}}},
		"directive newline":  {Directives: []Directive{{Key: "k", Value: "a\nb"}}},
	}
	for name, d := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if _, err := Encode(d); err == nil {
				t.Fatalf("expected error for %s", name)
			}
		})
	}
}

func TestActionsRowDecode(t *testing.T) {
	t.Parallel()
	// The canonical `actions` row is a single bare ID containing pipes.
	src := "actions\n  scale|rollout|restart\n"
	d, err := Decode([]byte(src))
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if len(d.Sections) != 1 || len(d.Sections[0].Rows) != 1 {
		t.Fatalf("unexpected shape: %+v", d)
	}
	r := d.Sections[0].Rows[0]
	if r.ID != "scale|rollout|restart" {
		t.Fatalf("expected pipe-joined ID, got %q", r.ID)
	}
	if len(r.Flags) != 0 || len(r.Fields) != 0 {
		t.Fatalf("expected ID-only row, got %+v", r)
	}
}
